
[window]
padding = { x = 12, y = 10 }
dynamic_padding = true
opacity = 1.0
blur = false


[font]
normal = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic.style = "Bold Italic"
size = 15
offset = { x = -1, y = 0 }

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-custom.toml"]
